<?php
error_reporting( E_ERROR );
header( 'Content-Type: text/html; charset=utf-8' );
require_once( str_replace( array( "\\", "/" ), array( MSDIRS, MSDIRS ), dirname( __FILE__ ) ) . MSDIRS . ".." . MSDIRS . "lib" . MSDIRS . "PHPExcel.php" );
$path = str_replace( array( "\\", "/" ), array( MSDIRS, MSDIRS ), dirname( __FILE__ ) ) . MSDIRS . ".." . MSDIRS . "exports" . MSDIRS . $survey_exp[ 'id' ] . ".xls";
$cacheMethod = PHPExcel_CachedObjectStorageFactory:: cache_to_phpTemp;
$cacheSettings = array( ' memoryCacheSize ' => '16MB');
PHPExcel_Settings::setCacheStorageMethod($cacheMethod, $cacheSettings);
$objPHPExcelWriter = new PHPExcel();

// Set document properties
$objPHPExcelWriter->getProperties()->setCreator("Modal Survey")
							 ->setLastModifiedBy("Modal Survey")
							 ->setTitle($survey_exp['name'])
							 ->setSubject($survey_exp['name'])
							 ->setDescription($survey_exp['name']." " . __( 'generated by', MODAL_SURVEY_TEXT_DOMAIN ) . " Modal Survey");

$csvheader_row = array(
    'font'  => array(
        'bold'  => true,
        'color' => array('rgb' => '000000'),
        'size'  => 10,
        'name'  => 'Helvetica'
    ));
$csvheader_normal_row = array(
    'font'  => array(
        'bold'  => false,
        'color' => array('rgb' => '000000'),
        'size'  => 10,
        'name'  => 'Helvetica'
    ));

			$c=1;
			$objPHPExcelWriter->getActiveSheet()->getColumnDimension('A')->setWidth(60);
			$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Survey ID', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $survey_exp['id'])->getStyle('A'.$c)->applyFromArray($csvheader_row);
			$c++;
			$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Survey Name', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $survey_exp['name'])->getStyle('A'.$c)->applyFromArray($csvheader_row);
			$c++;
			$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Generated', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, str_replace("'", "", $survey_exp['export_time']))->getStyle('A'.$c)->applyFromArray($csvheader_row);
			$c++;
			$objPHPExcelWriter->getActiveSheet()->getStyle('A'.$c.':B'.$c)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
			if ( $personal ) {
				$c++;
				$objPHPExcelWriter->getActiveSheet()->getColumnDimension('A')->setWidth(60);
				$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'User ID', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $survey_exp[ 'user_details' ]->autoid )->getStyle('A'.$c)->applyFromArray($csvheader_row);
				$c++;
				$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Username', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, ( $survey_exp[ 'user_details' ]->username ? $survey_exp[ 'user_details' ]->username : __( 'Not Specified', MODAL_SURVEY_TEXT_DOMAIN ) ))->getStyle('A'.$c)->applyFromArray($csvheader_row);
				$c++;
				$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Created', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $survey_exp[ 'user_details' ]->created)->getStyle('A'.$c)->applyFromArray($csvheader_row);
				$objPHPExcelWriter->getActiveSheet()->getStyle('A'.$c.':B'.$c)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
				$c++;
				$objPHPExcelWriter->getActiveSheet()->getColumnDimension('A')->setWidth(60);
				$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Email', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $survey_exp[ 'user_details' ]->email)->getStyle('A'.$c)->applyFromArray($csvheader_row);
				$c++;
				$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Name', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $survey_exp[ 'user_details' ]->name)->getStyle('A'.$c)->applyFromArray($csvheader_row);
				$objPHPExcelWriter->getActiveSheet()->getStyle('A'.$c.':B'.$c)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
				$c++;
				if ( ! empty( $survey_exp[ 'user_details' ]->custom ) ) {
					foreach ( unserialize( $survey_exp[ 'user_details' ]->custom ) as $muc_index=>$muc ) {
						$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, ucfirst( strtolower( $muc_index ) ))->setCellValue('B'.$c, $muc)->getStyle('A'.$c)->applyFromArray($csvheader_row);
						$objPHPExcelWriter->getActiveSheet()->getStyle('A'.$c.':B'.$c)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
						$c++;
					}
				}
				$objPHPExcelWriter->getActiveSheet()->getColumnDimension('A')->setWidth(60);
				$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Total Score', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $survey_exp[ 'user_details' ]->allscore)->getStyle('A'.$c)->applyFromArray($csvheader_row);
				$c++;
				$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Required Time', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $survey_exp[ 'user_details' ]->alltimer . __( 'sec', MODAL_SURVEY_TEXT_DOMAIN ))->getStyle('A'.$c)->applyFromArray($csvheader_row);
				$objPHPExcelWriter->getActiveSheet()->getStyle('A'.$c.':B'.$c)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
				$c++;
					$objPHPExcelWriter->setActiveSheetIndex(0)
					->setCellValue('A'.$c, __( 'Participant answers marked with stars: *', MODAL_SURVEY_TEXT_DOMAIN ) )->getStyle('A'.$c.':C'.$c)->applyFromArray($csvheader_normal_row);;
			}
			$c++;
			$c++;
			$objPHPExcelWriter->getActiveSheet()->getColumnDimension('A')->setWidth(60);
			if ( $personal ) {
				$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Question / Answer', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, __( 'Votes', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('C'.$c, __( 'Percentage', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('D'.$c, __( 'Score', MODAL_SURVEY_TEXT_DOMAIN ))->getStyle('A'.$c.':D'.$c)->applyFromArray($csvheader_row);
			}
			else {
				$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Question / Answer', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, __( 'Votes', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('C'.$c, __( 'Percentage', MODAL_SURVEY_TEXT_DOMAIN ))->getStyle('A'.$c.':C'.$c)->applyFromArray($csvheader_row);		
			}
			$c++;
			$totalscore = 0;
			foreach( $survey_exp[ 'questions' ] as $qkey=>$questions ) {
				$objPHPExcelWriter->setActiveSheetIndex(0)
				->setCellValue('A'.$c, $questions['name'])->getStyle('A'.$c)->applyFromArray($csvheader_normal_row);
				$objPHPExcelWriter->getActiveSheet()->getStyle('A'.$c)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
				$c++;
				foreach ($questions as $key=>$answer) {
					if ( is_numeric( $key ) ) {
						$marker = "";
						if ( $personal ) {
							if ( in_array( $key, $user_votes[ $qkey ] ) ) {
								$marker = "* ";
							}
							$aoptions = unserialize( $answer[ 'aoptions' ] );
							if ( $aoptions[ 4 ] != "" && in_array( $key, $user_votes[ $qkey ] ) ) {
								$score = $aoptions[ 4 ];
								$totalscore += $score;
							}
							else {
								$score = "";
							}
							$objPHPExcelWriter->setActiveSheetIndex(0)
							->setCellValue('A'.$c, $marker . $answer['answer'])->setCellValue('B'.$c, (string)$answer['count'])->setCellValue('C'.$c, (string)$answer['percentage'].'%')->setCellValue('D'.$c, $score)->getStyle('A'.$c)->applyFromArray($csvheader_normal_row);
							$objPHPExcelWriter->getActiveSheet()->getStyle('A'.$c.':D'.$c)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
						}
						else {
							$objPHPExcelWriter->setActiveSheetIndex(0)
							->setCellValue('A'.$c, $marker . $answer['answer'])->setCellValue('B'.$c, (string)$answer['count'])->setCellValue('C'.$c, (string)$answer['percentage'].'%')->getStyle('A'.$c)->applyFromArray($csvheader_normal_row);
							$objPHPExcelWriter->getActiveSheet()->getStyle('A'.$c.':C'.$c)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
						}
						$c++;
					}
				}
				$c++;
				$c++;
			}
				if ( $personal ) {
					$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Total:', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $questions['count'])->setCellValue('C'.$c, '')->setCellValue('D'.$c, $totalscore)->getStyle('A'.$c.':D'.$c)->applyFromArray($csvheader_row)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
				}
				else {
					$objPHPExcelWriter->setActiveSheetIndex(0)->setCellValue('A'.$c, __( 'Total:', MODAL_SURVEY_TEXT_DOMAIN ))->setCellValue('B'.$c, $questions['count'])->setCellValue('C'.$c, '')->getStyle('A'.$c.':C'.$c)->applyFromArray($csvheader_row)->getAlignment()->setWrapText(true)->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
				}
				$objPHPExcelWriter->getActiveSheet()->getColumnDimension('A')->setAutoSize(true);
				$objPHPExcelWriter->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
				$objPHPExcelWriter->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
				$objPHPExcelWriter->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcelWriter, 'Excel5');
$objWriter->save($path);
if (!empty($objWriter)) $result = "success";
else $result = __( 'Write error', MODAL_SURVEY_TEXT_DOMAIN );
 ?>